### ISSUE TITLE
'Serial' object has no attribute 'reset_input_buffer'

### ISSUE THREAD

**Issue by wkyoun** [anuragmakineni/ros_lightware#2]
I tried to run the your code with SF02 Lidar(Lightware)
, but following error occur,

Would you please let me know how to fix it?

wkyoun@wkyoun-XPS-13-9343:~/catkin_ws$ rosrun lightware_ros lightware_driver.py

    Traceback (most recent call last):
      File "/home/wkyoun/catkin_ws/src/lightware_ros/nodes/lightware_driver.py", line 50, in <module>
        lightware_ros()
      File "/home/wkyoun/catkin_ws/src/lightware_ros/nodes/lightware_driver.py", line 24, in lightware_ros
        ser.reset_input_buffer()
    AttributeError: 'Serial' object has no attribute 'reset_input_buffer'

**Comment by anuragmakineni** [comment]
What version of PySerial are you using?

**Comment by wkyoun** [comment]
how can I check the version of Pyserial?

**Comment by wkyoun** [comment]
Is your code supposed to be working with SF02 Lidar(Lightware)?

Thank you for the help

**Comment by wkyoun** [comment]
wkyoun@wkyoun-XPS-13-9343:~$ pip install pyserial

    Requirement already satisfied (use --upgrade to upgrade): pyserial in /usr/lib/python2.7/dist-packages
Cleaning up...

I guess mine is python2.7

**Comment by anuragmakineni** [comment]
Hi won13y, 

I haven't tested this code on the SF02. I originally wrote it to interface with the SF10B. If the serial interface is the same between the sensors, this code should work. Note that this code isn't very polished as it was hacked together. Some of the sensor parameters are hardcoded and you may want to update these for the SF02.

To check the version of pyserial run the following command in your terminal:

 `pip show pyserial | grep Version`

I suspect that this error is because you're on an old version of PySerial.

**Comment by wkyoun** [comment]
Your code is working right now after I ugrade pyserial Version: 3.2.1
Thank  you very much 

Here is the command list that I did in order to work with SF02

https://github.com/anuragmakineni/lightware_ros.git
chmod +x lightware_driver.py
sudo pip install --upgrade pyserial

rosrun lightware_ros lightware_driver.py

**Comment by anuragmakineni** [comment]
Great! As I mentioned, I've never tested this code on the SF02. Please let me know if it works for you! I'm closing this issue now.
